baseURL = "http://evantrimble.com"
languageCode = "en-us"
title = "evantrimble"
newContentEditor = "atom"
theme = "gohugo-theme-ananke"
pygmentsStyle = "native"
publishDir = "public"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 5 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = ""
  facebook = "https://www.facebook.com/evantrimble"
  twitter = "https://twitter.com/evantrimble"
  instagram = "https://www.instagram.com/gyurme/"
  youtube = ""
  github = ""
  linkedin = "https://www.linkedin.com/in/evantrimble/"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = ""
  recent_posts_number = 2
